env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - ghc --version

 - travis_retry cabal update

 - cabal install --constraint=transformers\ installed happy alex
 - export PATH=$HOME/.cabal/bin:$PATH

install:
 - cabal install --only-dependencies --enable-tests
 - cabal configure --enable-tests

script:
 - cabal build
 - cabal test --show-details=always

notifications:
  flowdock:
    secure: "Q5YiZr4X5fV5HWRMvNrhZRHG2KyIs8M1VA+WgeRkh5qEaAgXii2Hr0ncWwIrLiLWU6657rzbigjrTU7QwtMse2cjRTcylV1ZJDhu8Jca401VyfIBNP3suiOlPZrKNFXBdGQQyOVm93Y/gdeJwgcO1BkuUSzBAos4s9LFXZLI8Fo="
