flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- adjunctions-4.2.1
- ansi-terminal-0.6.2.1
- ansi-wl-pprint-0.6.7.2
- attoparsec-0.13.0.0
- base-orphans-0.3.3
- bifunctors-5
- blaze-builder-0.4.0.1
- blaze-html-0.8.0.2
- blaze-markup-0.7.0.2
- case-insensitive-1.2.0.4
- comonad-4.2.6
- conduit-1.2.4.2
- conduit-extra-1.1.9
- contravariant-1.3.1.1
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.4.4
- dlist-0.7.1.1
- double-conversion-2.0.1.0
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- free-4.12.1
- hashable-1.2.3.3
- hostname-1.0
- HUnit-1.2.5.2
- kan-extensions-4.2.2
- lens-4.11
- lifted-base-0.2.3.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.0
- old-locale-1.0.0.7
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-1.5.2.1
- regex-base-0.93.2
- regex-posix-0.95.2
- resourcet-1.1.5
- scientific-0.3.3.8
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- StateVar-1.1.0.0
- stm-2.4.4
- streaming-commons-0.1.12.1
- syb-0.5.1
- tagged-0.8.0.1
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.1
- text-1.2.1.1
- text-format-0.3.1.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.10.12.3
- void-0.7
- xml-1.3.14
- xml-conduit-1.3.0
- xml-lens-0.1.6.3
- xml-types-0.3.5
- zlib-0.6.1.1
resolver: ghc-7.10
